.:
  - poll-interval: &poll-interval {poll-interval: 1000}
  - battery-interval: &battery-interval {poll-interval: 30000}
bar:
  location: bottom
  layer: bottom
  background: 111111ff
  font: "Iosevka NF:size=16:antialias=true:autohint:true,UbuntuMono Nerd Font:size=18:antialias=true:autohint:true"
  height: 22
  spacing: 12
  margin: 6

  border:
    margin: 6
    top-margin: 0

  left:
#    - script:
#        path: /usr/bin/playerctl
#        args:
#          - "--follow"
#          - metadata
#          - "-f"
#          - |
#            status|string|{{status}}
#            artist|string|{{artist}}
#            title|string|{{title}}
#
#        content:
#          map:
#            default: {empty: {}}
#            conditions:
#              status == "Playing": {string: {text: "  {artist} - {title}"}}
    - mem:
        <<: *poll-interval
        content: {string: {text: "Mem: {used:mib} MB/{total:mib} MB"}}
    # Load average
    - script:
        <<: *poll-interval
        path: /usr/bin/awk
        args:
          - '{print "av1|float|"$1"\nav5|float|"$2"\nav15|float|"$3"\n"}'
          - /proc/loadavg
        content: {string: {text: "Avg: {av1} {av5} {av15}"}}
    # Temperature
    - script:
        <<: *poll-interval
        path: /usr/bin/awk
        args:
          - '{ printf "temp|float|%f\n\n", $1/1000 }'
          - /sys/class/hwmon/hwmon3/temp1_input
        content:
          ramp:
            tag: temp
            min: 0
            max: 100
            items:
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
    - cpu:
        <<: *poll-interval
        content:
          map:
            conditions:
              id < 0:
                - string: {text: "CPU: {cpu}%"}
    - battery:
        name: BAT0
        <<: *battery-interval
        content:
          map:
            conditions:
              state == "full": {string: {text: "󰁹 {capacity}%"}}
              state == "unknown": {string: {text: "BAT: {capacity}%"}}
              state == "discharging":
                list:
                  items:
                    - ramp:
                        tag: capacity
                        items:
                          - string: {text: "󰂎"}
                          - string: {text: "󰁺"}
                          - string: {text: "󰁻"}
                          - string: {text: "󰁼"}
                          - string: {text: "󰁽"}
                          - string: {text: "󰁾"}
                          - string: {text: "󰁿"}
                          - string: {text: "󰂀"}
                          - string: {text: "󰂁"}
                          - string: {text: "󰂂"}
                          - string: {text: "󰁹"}
                    - string: {text: " {capacity}%"}
                    - string: {text: " ETA: {estimate}"}
              state == "charging":
                list:
                  items:
                    - ramp:
                        tag: capacity
                        items:
                          - string: {text: "󰢟"}
                          - string: {text: "󰢜"}
                          - string: {text: "󰂆"}
                          - string: {text: "󰂇"}
                          - string: {text: "󰂈"}
                          - string: {text: "󰢝"}
                          - string: {text: "󰂉"}
                          - string: {text: "󰢞"}
                          - string: {text: "󰂊"}
                          - string: {text: "󰂋"}
                          - string: {text: "󰂅"}
                    - string: {text: " {capacity}%"}
                    - string: {text: " ETA: {estimate}"}
    - backlight:
        name: amdgpu_bl0
        content: {string: {text: "BL: {percent}%"}}
    - removables:
        content:
          map:
            conditions:
              ~mounted:
                string:
                  on-click:
                    left: /usr/bin/udisksctl mount -b {device}
                    middle: /usr/bin/udisksctl power-off -b {device}
                  text: "{label}"
                  foreground: 888888ff
              mounted:
                string:
                    on-click: /usr/bin/udisksctl unmount -b {device}
                    text: "{label}"
    - network:
        <<: *poll-interval
        content:
          map:
            default: {empty: {}}
            conditions:
              state == "up" && name == "eno1":
                - string: {text: "󰈀 "}
                - map:
                    default: {string: {text: "{dl-speed}"}}
                    conditions:
                      dl-speed > 1073741824: {string: {text: "{dl-speed:gib} Gi"}}
                      dl-speed > 1048576: {string: {text: "{dl-speed:mib} Mi"}}
                      dl-speed > 1024: {string: {text: "{dl-speed:kib} Ki"}}
                - string: {text: " 󱦳󱦲 "}
                - map:
                    default: {string: {text: "{ul-speed}"}}
                    conditions:
                      ul-speed > 1073741824: {string: {text: "{ul-speed:gib} Gi"}}
                      ul-speed > 1048576: {string: {text: "{ul-speed:mib} Mi"}}
                      ul-speed > 1024: {string: {text: "{ul-speed:kib} Ki"}}
    - network:
        <<: *poll-interval
        content:
          map:
            default: {empty: {}}
            conditions:
              state == "up" && name == "wlo1":
                - ramp:
                    tag: quality
                    items:
                      - string: {text: "󰤯"}
                      - string: {text: "󰤟"}
                      - string: {text: "󰤢"}
                      - string: {text: "󰤥"}
                      - string: {text: "󰤨"}
                - string: {text: " {ssid} "}
                - map:
                    default: {string: {text: "{dl-speed}"}}
                    conditions:
                      dl-speed > 1073741824: {string: {text: "{dl-speed:gib} Gi"}}
                      dl-speed > 1048576: {string: {text: "{dl-speed:mib} Mi"}}
                      dl-speed > 1024: {string: {text: "{dl-speed:kib} Ki"}}
                - string: {text: " 󱦳󱦲 "}
                - map:
                    default: {string: {text: "{ul-speed}"}}
                    conditions:
                      ul-speed > 1073741824: {string: {text: "{ul-speed:gib} Gi"}}
                      ul-speed > 1048576: {string: {text: "{ul-speed:mib} Mi"}}
                      ul-speed > 1024: {string: {text: "{ul-speed:kib} Ki"}}
#    - disk-io:
#        <<: *interval
#        content:
#          map:
#            conditions:
#              device == sda:
#                list:
#                  items:
#                    - string: {text: "{device}: "}
#                    - string: {text: "r "}
#                    - map:
#                        default: {string: {text: "{read_speed} B/s"}}
#                        conditions:
#                          read_speed > 1073741824: {string: {text: "{read_speed:gib} GB/s"}}
#                          read_speed > 1048576: {string: {text: "{read_speed:mib} MB/s"}}
#                          read_speed > 1024: {string: {text: "{read_speed:kib} KB/s"}}
#                    - string: {text: " | "}
#                    - string: {text: "w "}
#                    - map:
#                        default: {string: {text: "{write_speed} B/s"}}
#                        conditions:
#                          write_speed > 1073741824: {string: {text: "{write_speed:gib} GB/s"}}
#                          write_speed > 1048576: {string: {text: "{write_speed:mib} MB/s"}}
#                          write_speed > 1024: {string: {text: "{write_speed:kib} KB/s"}}
#                    - string: {text: "  "}
#              device == sdb:
#                list:
#                  items:
#                    - string: {text: "{device}: "}
#                    - string: {text: "r "}
#                    - map:
#                        default: {string: {text: "{read_speed} B/s"}}
#                        conditions:
#                          read_speed > 1073741824: {string: {text: "{read_speed:gib} GB/s"}}
#                          read_speed > 1048576: {string: {text: "{read_speed:mib} MB/s"}}
#                          read_speed > 1024: {string: {text: "{read_speed:kib} KB/s"}}
#                    - string: {text: " | "}
#                    - string: {text: "w "}
#                    - map:
#                        default: {string: {text: "{write_speed} B/s"}}
#                        conditions:
#                          write_speed > 1073741824: {string: {text: "{write_speed:gib} GB/s"}}
#                          write_speed > 1048576: {string: {text: "{write_speed:mib} MB/s"}}
#                          write_speed > 1024: {string: {text: "{write_speed:kib} KB/s"}}
#                    - string: {text: "  "}
#
