.:
  - interval: &interval {interval: 1000}
  - poll-interval: &poll-interval {poll-interval: 1}
  - battery-interval: &battery-interval {poll-interval: 30}
bar:
  location: bottom
  layer: bottom
  background: 111111ff
  font: "UbuntuMono Nerd Font:size=18:antialias=true:autohint:true"
  height: 20
  spacing: 12
  margin: 6

  border:
    margin: 6
    top-margin: 0

  left:
    - script:
        path: /usr/bin/playerctl
        args:
          - "--follow"
          - metadata
          - "-f"
          - |
            status|string|{{status}}
            artist|string|{{artist}}
            title|string|{{title}}

        content:
          map:
            default: {empty: {}}
            conditions:
              status == "Playing": {string: {text: "  {artist} - {title}"}}
    - mem:
        <<: *interval
        content: {string: {text: "Mem: {used:mib} MB/{total:mib} MB"}}
    # Load average
    - script:
        <<: *poll-interval
        path: /usr/bin/awk
        args:
          - '{print "av1|float|"$1"\nav5|float|"$2"\nav15|float|"$3"\n"}'
          - /proc/loadavg
        content: {string: {text: "Avg: {av1} {av5} {av15}"}}
    # Temperature
    - script:
        <<: *poll-interval
        path: /usr/bin/awk
        args:
          - '{ printf "temp|float|%f\n\n", $1/1000 }'
          - /sys/class/hwmon/hwmon1/temp1_input
        content:
          ramp:
            tag: temp
            min: 20
            max: 105
            items:
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
    - cpu:
        <<: *interval
        content: {string: {text: "CPU: {cpu}%"}}
    - battery:
        name: BAT0
        <<: *battery-interval
        content:
          map:
            conditions:
              state == "full": {string: {text: " {capacity}%"}}
              state == "unknown": {string: {text: "BAT: {capacity}%"}}
              state == "discharging":
                list:
                  items:
                    - ramp:
                        tag: capacity
                        items:
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                    - string: {text: " {capacity}%"}
                    - string: {text: " ETA: {estimate}"}
              state == "charging":
                list:
                  items:
                    - ramp:
                        tag: capacity
                        items:
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                          - string: {text: ""}
                    - string: {text: " {capacity}%"}
                    - string: {text: " ETA: {estimate}"}
    - backlight:
        name: amdgpu_bl0
        content: {string: {text: "BL: {percent}%"}}
    - network:
        name: eno1
        <<: *poll-interval
        content:
          map:
            default: {empty: {}}
            conditions:
              state == "up":
                list:
                  items:
                    - string: {text: "Net({name}): "}
                    - map:
                        default: {string: {text: "{dl-speed}"}}
                        conditions:
                          dl-speed > 1073741824: {string: {text: "{dl-speed:gib} Gi"}}
                          dl-speed > 1048576: {string: {text: "{dl-speed:mib} Mi"}}
                          dl-speed > 1024: {string: {text: "{dl-speed:kib} Ki"}}
                    - string: {text: " ↓↑ "}
                    - map:
                        default: {string: {text: "{ul-speed}"}}
                        conditions:
                          ul-speed > 1073741824: {string: {text: "{ul-speed:gib} Gi"}}
                          ul-speed > 1048576: {string: {text: "{ul-speed:mib} Mi"}}
                          ul-speed > 1024: {string: {text: "{ul-speed:kib} Ki"}}
    - network:
        name: wlo1
        <<: *poll-interval
        content:
          map:
            default: {empty: {}}
            conditions:
              state == "up":
                list:
                  items:
                    - string: {text: "Net({name})"}
                    - string: {text: " - "}
                    - string: {text: "SSID({ssid})"}
                    - string: {text: " - "}
                    - string: {text: "signal({signal}): "}
                    - map:
                        default: {string: {text: "{dl-speed}"}}
                        conditions:
                          dl-speed > 1073741824: {string: {text: "{dl-speed:gib} Gi"}}
                          dl-speed > 1048576: {string: {text: "{dl-speed:mib} Mi"}}
                          dl-speed > 1024: {string: {text: "{dl-speed:kib} Ki"}}
                    - string: {text: " ↓↑ "}
                    - map:
                        default: {string: {text: "{ul-speed}"}}
                        conditions:
                          ul-speed > 1073741824: {string: {text: "{ul-speed:gib} Gi"}}
                          ul-speed > 1048576: {string: {text: "{ul-speed:mib} Mi"}}
                          ul-speed > 1024: {string: {text: "{ul-speed:kib} Ki"}}
    - removables:
        content:
          map:
            conditions:
              ~mounted:
                string:
                  on-click: /usr/bin/udisksctl mount -b {device}
                  text: "{label}"
                  foreground: 888888ff
              mounted:
                string:
                    on-click: /usr/bin/udisksctl umount -b {device}
                    text: "{label}"
