bar:
  location: bottom
  layer: bottom
  background: 111111ff
  font: "UbuntuMono Nerd Font:size=18:antialias=true:autohint:true"
  height: 20
  spacing: 12
  margin: 6

  border:
    margin: 6
    top-margin: 0

  left:
    - script:
        path: /usr/bin/playerctl
        args:
          - "--follow"
          - metadata
          - "-f"
          - |
            status|string|{{status}}
            artist|string|{{artist}}
            title|string|{{title}}

        content:
          map:
            default: {empty: {}}
            conditions:
              status == "Playing": {string: {text: "  {artist} - {title}"}}
    - mem:
        interval: 5000
        content: {string: {text: "Mem: {used:mib} MB/{total:mib} MB"}}
    # Load average
    - script:
        poll-interval: 5
        path: /usr/bin/awk
        args:
          - '{print "av1|float|"$1"\nav5|float|"$2"\nav15|float|"$3"\n"}'
          - /proc/loadavg
        content: {string: {text: "Avg: {av1} {av5} {av15}"}}
    # Temperature
    - script:
        poll-interval: 5
        path: /usr/bin/awk
        args:
          - '{ printf "temp|range:20-105|%i\n\n", int($1/1000) }'
          - /sys/class/hwmon/hwmon0/temp1_input
        content:
          ramp:
            tag: temp
            items:
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
              - string: {text: " {temp}°C"}
    - cpu:
        interval: 5000
        content: {string: {text: "CPU: {cpu}%"}}
    - battery:
        name: BAT0
        poll-interval: 60
        content:
          map:
            conditions:
              state == "full": {string: {text: " {capacity}%"}}
              state == "unknown": {string: {text: "BAT: {capacity}%"}}
              state == "discharging":
                ramp:
                  tag: capacity
                  items:
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
              state == "charging":
                ramp:
                  tag: capacity
                  items:
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
                    - string: {text: " {capacity}% ETA: {estimate}"}
    - backlight:
        name: amdgpu_bl0
        content: {string: {text: "BL: {percent}%"}}
# Yambar only reports network speed in Mbit/s
#    - script:
#        path: /usr/local/bin/network
#        args: [ -s ]
#        content: {string: {text: "Net: {rx-bitrate} ↓↑ {tx-bitrate}"}}

    - network:
        name: eno1
        poll-interval: 5
        content:
          map:
            conditions:
              state == "down": {empty: {}}
              state == "up": {string: {text: "Net({name}): {dl-speed:kib} Ki ↓↑ {ul-speed:kib} Ki"}}
    - network:
        name: wlo1
        poll-interval: 5
        content:
          map:
            conditions:
              state == "down": {empty: {}}
              state == "up": {string: {text: "Net({name}) - SSID({ssid}) - signal({signal}): {dl-speed:kib} Ki ↓↑ {ul-speed:kib} Ki"}}
