bar:
  location: top
  layer: bottom
  background: 222222ff
  font: "Iosevka Nerd Font:size=16:antialias=true:autohint:true,UbuntuMono Nerd Font:size=18:antialias=true:autohint:true,Joypixels"
  height: 22
  spacing: 6
  right-margin: 6
  border:
    margin: 6
    bottom-margin: 0

  left:
    - script:
        path: /usr/local/bin/dwl-tags.sh
        args: [ eDP-1 ]
        anchors:
          - occupied: &occupied {foreground: ffffffff}
          - default: &default {foreground: aaaaaaff}
          - urgent: &urgent {deco: { background: {color: ff0000ff}}}
          - focused: &focused {deco: { background: {color: 6000ffff}}}
          - floating: &floating {deco: {underline: {size: 2, color: ffffffff}}}
        content:
          - map:
              conditions:
                tag_0_occupied:
                  map:
                    conditions:
                      tag_0_focused:
                          map:
                            conditions:
                              tag_0_urgent: {string: {text: " {tag_0} ", <<: [*urgent, *occupied]}}
                              ~tag_0_urgent: {string: {text: " {tag_0} ", <<: [*focused, *occupied]}}
                      ~tag_0_focused:
                          map:
                            conditions:
                              tag_0_urgent: {string: {text: " {tag_0} ", <<: *urgent}}
                              ~tag_0_urgent: {string: {text: " {tag_0} ", <<: *occupied}}
                ~tag_0_occupied:
                  map:
                    conditions:
                      tag_0_focused: {string: {text: " {tag_0} ", <<: [*focused, *default]}}
                      ~tag_0_focused: {string: {text: " {tag_0} ", <<: *default}}
          - map:
              conditions:
                tag_1_occupied:
                  map:
                    conditions:
                      tag_1_focused:
                          map:
                            conditions:
                              tag_1_urgent: {string: {text: " {tag_1} ", <<: [*urgent, *occupied]}}
                              ~tag_1_urgent: {string: {text: " {tag_1} ", <<: [*focused, *occupied]}}
                      ~tag_1_focused:
                        map:
                          conditions:
                            tag_1_urgent: {string: {text: " {tag_1} ", <<: *urgent}}
                            ~tag_1_urgent: {string: {text: " {tag_1} ", <<: *occupied}}
                ~tag_1_occupied:
                  map:
                    conditions:
                      tag_1_focused: {string: {text: " {tag_1} ", <<: [*focused, *default]}}
                      ~tag_1_focused: {string: {text: " {tag_1} ", <<: *default}}
          - map:
              conditions:
                tag_2_occupied:
                  map:
                    conditions:
                      tag_2_focused:
                          map:
                            conditions:
                              tag_2_urgent: {string: {text: " {tag_2} ", <<: [*urgent, *occupied]}}
                              ~tag_2_urgent: {string: {text: " {tag_2} ", <<: [*focused, *occupied]}}
                      ~tag_2_focused:
                        map:
                          conditions:
                            tag_2_urgent: {string: {text: " {tag_2} ", <<: *urgent}}
                            ~tag_2_urgent: {string: {text: " {tag_2} ", <<: *occupied}}
                ~tag_2_occupied:
                  map:
                    conditions:
                      tag_2_focused: {string: {text: " {tag_2} ", <<: [*focused, *default]}}
                      ~tag_2_focused: {string: {text: " {tag_2} ", <<: *default}}
          - map:
              conditions:
                tag_3_occupied:
                  map:
                    conditions:
                      tag_3_focused:
                          map:
                            conditions:
                              tag_3_urgent: {string: {text: " {tag_3} ", <<: [*urgent, *occupied]}}
                              ~tag_3_urgent: {string: {text: " {tag_3} ", <<: [*focused, *occupied]}}
                      ~tag_3_focused:
                        map:
                          conditions:
                            tag_3_urgent: {string: {text: " {tag_3} ", <<: *urgent}}
                            ~tag_3_urgent: {string: {text: " {tag_3} ", <<: *occupied}}
                ~tag_3_occupied:
                  map:
                    conditions:
                      tag_3_focused: {string: {text: " {tag_3} ", <<: [*focused, *default]}}
                      ~tag_3_focused: {string: {text: " {tag_3} ", <<: *default}}
          - map:
              conditions:
                tag_4_occupied:
                  map:
                    conditions:
                      tag_4_focused:
                          map:
                            conditions:
                              tag_4_urgent: {string: {text: " {tag_4} ", <<: [*urgent, *occupied]}}
                              ~tag_4_urgent: {string: {text: " {tag_4} ", <<: [*focused, *occupied]}}
                      ~tag_4_focused:
                        map:
                          conditions:
                            tag_4_urgent: {string: {text: " {tag_4} ", <<: *urgent}}
                            ~tag_4_urgent: {string: {text: " {tag_4} ", <<: *occupied}}
                ~tag_4_occupied:
                  map:
                    conditions:
                      tag_4_focused: {string: {text: " {tag_4} ", <<: [*focused, *default]}}
                      ~tag_4_focused: {string: {text: " {tag_4} ", <<: *default}}
          - map:
              conditions:
                tag_5_occupied:
                  map:
                    conditions:
                      tag_5_focused:
                          map:
                            conditions:
                              tag_5_urgent: {string: {text: " {tag_5} ", <<: [*urgent, *occupied]}}
                              ~tag_5_urgent: {string: {text: " {tag_5} ", <<: [*focused, *occupied]}}
                      ~tag_5_focused:
                        map:
                          conditions:
                            tag_5_urgent: {string: {text: " {tag_5} ", <<: *urgent}}
                            ~tag_5_urgent: {string: {text: " {tag_5} ", <<: *occupied}}
                ~tag_5_occupied:
                  map:
                    conditions:
                      tag_5_focused: {string: {text: " {tag_5} ", <<: [*focused, *default]}}
                      ~tag_5_focused: {string: {text: " {tag_5} ", <<: *default}}
          - map:
              conditions:
                tag_6_occupied:
                  map:
                    conditions:
                      tag_6_focused:
                          map:
                            conditions:
                              tag_6_urgent: {string: {text: " {tag_6} ", <<: [*urgent, *occupied]}}
                              ~tag_6_urgent: {string: {text: " {tag_6} ", <<: [*focused, *occupied]}}
                      ~tag_6_focused:
                        map:
                          conditions:
                            tag_6_urgent: {string: {text: " {tag_6} ", <<: *urgent}}
                            ~tag_6_urgent: {string: {text: " {tag_6} ", <<: *occupied}}
                ~tag_6_occupied:
                  map:
                    conditions:
                      tag_6_focused: {string: {text: " {tag_6} ", <<: [*focused, *default]}}
                      ~tag_6_focused: {string: {text: " {tag_6} ", <<: *default}}
          - map:
              conditions:
                tag_7_occupied:
                  map:
                    conditions:
                      tag_7_focused:
                          map:
                            conditions:
                              tag_7_urgent: {string: {text: " {tag_7} ", <<: [*urgent, *occupied]}}
                              ~tag_7_urgent: {string: {text: " {tag_7} ", <<: [*focused, *occupied]}}
                      ~tag_7_focused:
                        map:
                          conditions:
                            tag_7_urgent: {string: {text: " {tag_7} ", <<: *urgent}}
                            ~tag_7_urgent: {string: {text: " {tag_7} ", <<: *occupied}}
                ~tag_7_occupied:
                  map:
                    conditions:
                      tag_7_focused: {string: {text: " {tag_7} ", <<: [*focused, *default]}}
                      ~tag_7_focused: {string: {text: " {tag_7} ", <<: *default}}
          - map:
              conditions:
                tag_8_occupied:
                  map:
                    conditions:
                      tag_8_focused:
                          map:
                            conditions:
                              tag_8_urgent: {string: {text: " {tag_8} ", <<: [*urgent, *occupied]}}
                              ~tag_8_urgent: {string: {text: " {tag_8} ", <<: [*focused, *occupied]}}
                      ~tag_8_focused:
                        map:
                          conditions:
                            tag_8_urgent: {string: {text: " {tag_8} ", <<: *urgent}}
                            ~tag_8_urgent: {string: {text: " {tag_8} ", <<: *occupied}}
                ~tag_8_occupied:
                  map:
                    conditions:
                      tag_8_focused: {string: {text: " {tag_8} ", <<: [*focused, *default]}}
                      ~tag_8_focused: {string: {text: " {tag_8} ", <<: *default}}
          - map:
              conditions:
                tag_9_occupied:
                  map:
                    conditions:
                      tag_9_focused:
                          map:
                            conditions:
                              tag_9_urgent: {string: {text: " {tag_9} ", <<: [*urgent, *occupied]}}
                              ~tag_9_urgent: {string: {text: " {tag_9} ", <<: [*focused, *occupied]}}
                      ~tag_9_focused:
                        map:
                          conditions:
                            tag_9_urgent: {string: {text: " {tag_9} ", <<: *urgent}}
                            ~tag_9_urgent: {string: {text: " {tag_9} ", <<: *occupied}}
                ~tag_9_occupied:
                  map:
                    conditions:
                      tag_9_focused: {string: {text: " {tag_9} ", <<: [*focused, *default]}}
                      ~tag_9_focused: {string: {text: " {tag_9} ", <<: *default}}
          - list:
              left-margin: 6
              spacing: 6
              items:
                - string: {text: "{layout}"}
                - map:
                    conditions:
                      floating: {string: {text: "{title}", max: 78, <<: *floating}}
                      ~floating: {string: {text: "{title}", max: 78}}
  right:
    - pulse:
        content:
          map:
            conditions:
              ~online: {string: {text: "ﱝ", foreground: 888888ff}}
              online:
                map:
                  on-click:
                    left: /usr/bin/pactl set-sink-mute @DEFAULT_SINK@ toggle
                    wheel-up: /usr/bin/pactl set-sink-volume @DEFAULT_SINK@ +2%
                    wheel-down: /usr/bin/pactl set-sink-volume @DEFAULT_SINK@ -2%
                  conditions:
                    sink_muted: {string: {text: "婢 {sink_percent}%", foreground: 888888ff}}
                    ~sink_muted:
                      ramp:
                        tag: sink_percent
                        items:
                          - string: {text: "奄 {sink_percent}%"}
                          - string: {text: "奔 {sink_percent}%"}
                          - string: {text: "墳 {sink_percent}%"}
                          - string: {text: " {sink_percent}%"}
    - clock:
        time-format: "%X"
        date-format: "%a %x"
        content:
          - list:
              spacing: 6
              items:
                - string: {text: " {time}"}
                - string: {text: " {date}"}
