# Don't insert a blank line between shell prompts
add_newline = false

format = "${custom.os}$all"
right_format = """$status$cmd_duration$time"""


[cmd_duration]
min_time = 100
show_milliseconds = true

[directory]
truncate_to_repo = false
truncation_length = 0

[git_metrics]
disabled = false

[git_status]
conflicted = "$count✗"
ahead = "$count⇡"
behind = "$count⇣"
diverged = "$ahead_count⇡⇣$behind_count"
stashed = "$count$"
modified = "$count "
staged = "$count+"
renamed = "$count»"
deleted = "$count✘"
style = "bold purple"

[jobs]
format = "[$number$symbol]($style) "

[status]
disabled = false

[time]
disabled = false

[custom.os]
description = "Show distro icon"
os          = "linux"
symbol      = ""
format      = "$symbol [$output]($style) "
style       = "bold purple"
when        = "true"
command     = '''
. /etc/os-release
case "$ID" in
	arch)
		echo ""
	;;
	centos) 
		echo ""
	;;
	debian)
		echo ""
	;;
	fedora)
		echo ""
	;;
	gentoo)
		echo ""
	;;
	linuxmint)
		echo ""
	;;
	suse|opensuse)
		echo ""
	;;
	ubuntu)
		echo ""
	;;
	elementary)
		echo ""
	;;
	*)
		echo ""
	;;
esac
'''
