# Don't insert a blank line between shell prompts
add_newline = false

format = "$os$all"
right_format = """$status$cmd_duration$time"""
continuation_prompt = "[▶▶ ](green)"

[c]
commands = [ ["sh", "-c", "${CC} --version"], ["cc", "--version"], ["gcc", "--version"], ["clang", "--version"] ]

[os]
disabled = false
style = "bold purple"
[os.symbols]
Gentoo = "  "

[cmd_duration]
min_time = 100
show_milliseconds = true

[directory]
truncate_to_repo = false
truncation_length = 0

[git_metrics]
disabled = false

[git_status]
conflicted = "$count󰞇 "
ahead = "$count󱦲 "
behind = "$count󱦳 "
diverged = "$ahead_count󱦲󱦳$behind_count "
stashed = "$count$ "
modified = "$count "
staged = "$count󰐕 "
renamed = "$count󰄾 "
deleted = "$count "
style = "bold purple"

[jobs]
format = "[$number$symbol]($style) "

[status]
disabled = false

[time]
disabled = false
