[font]
normal.family = "Iosevka NFM"
size = 9.5

[window]
decorations = "none"
opacity = 0.75
padding.x = 0
padding.y = 0

[colors]
primary.background = "#000000"
primary.foreground = "#dddddd"

[colors.bright]
black = "#767676"
blue = "#1a8fff"
cyan = "#14ffff"
green = "#23fd00"
magenta = "#fd28ff"
red = "#f2201f"
white = "#ffffff"
yellow = "#fffd00"

[colors.normal]
black = "#000000"
blue = "#0d73cc"
cyan = "#0dcdcd"
green = "#19cb00"
magenta = "#cb1ed1"
red = "#cc0403"
white = "#dddddd"
yellow = "#cecb00"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "P"
mods = "Control|Shift|Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "N"
mods = "Control|Shift|Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Shift|Alt"

[[keyboard.bindings]]
action = "SearchForward"
key = "S"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchConfirm"
key = "Return"
mode = "Search"

[[keyboard.bindings]]
action = "SearchCancel"
key = "G"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "N"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "P"
mode = "Search"
mods = "Control"
